name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: uni-und-kind-website
          path: |
            ./*/*
            !.*/*
          if-no-files-found: error