name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: jekyll build
        uses: mbursi/jekyll-build-only-action@v1.0.0
      - name: save artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: uni-und-kind-website
          path: ./_site/*
          if-no-files-found: error